language: php

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: LARAVEL='5.5.*' TESTBENCH='3.5.*'
    - php: 7.1
      env: LARAVEL='5.6.*' TESTBENCH='3.6.*'
    - php: 7.1
      env: LARAVEL='5.7.*' TESTBENCH='3.7.*'
    - php: 7.1
      env: LARAVEL='5.8.*' TESTBENCH='3.8.*'
    - php: 7.2
      env: LARAVEL='5.5.*' TESTBENCH='3.5.*'
    - php: 7.2
      env: LARAVEL='5.6.*' TESTBENCH='3.6.*'
    - php: 7.2
      env: LARAVEL='5.7.*' TESTBENCH='3.7.*'
    - php: 7.2
      env: LARAVEL='5.8.*' TESTBENCH='3.8.*'
    - php: 7.2
      env: LARAVEL='6.*' TESTBENCH='4.*'
    - php: 7.2
      env: LARAVEL='7.*' TESTBENCH='5.*'
    - php: 7.3
      env: LARAVEL='5.5.*' TESTBENCH='3.5.*'
    - php: 7.3
      env: LARAVEL='5.6.*' TESTBENCH='3.6.*'
    - php: 7.3
      env: LARAVEL='5.7.*' TESTBENCH='3.7.*'
    - php: 7.3
      env: LARAVEL='5.8.*' TESTBENCH='3.8.*'
    - php: 7.3
      env: LARAVEL='6.*' TESTBENCH='4.*'
    - php: 7.3
      env: LARAVEL='7.*' TESTBENCH='5.*'
    - php: 7.3
      env: LARAVEL='8.*' TESTBENCH='6.*'
    - php: 7.4
      env: LARAVEL='5.8.*' TESTBENCH='3.8.*'
    - php: 7.4
      env: LARAVEL='6.*' TESTBENCH='4.*'
    - php: 7.4
      env: LARAVEL='7.*' TESTBENCH='5.*'
    - php: 7.4
      env: LARAVEL='8.*' TESTBENCH='6.*'
  fast_finish: true

before_script:
  - composer config discard-changes true

before_install:
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
